/*Copyright (c) 2016-2017 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.job1111;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RefWeldProcedures generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`REF_WeldProcedures`")
public class RefWeldProcedures implements Serializable {

    private Integer id;
    private String procedure;
    private String material;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`Procedure`", nullable = true, length = 45)
    public String getProcedure() {
        return this.procedure;
    }

    public void setProcedure(String procedure) {
        this.procedure = procedure;
    }

    @Column(name = "`Material`", nullable = true, length = 45)
    public String getMaterial() {
        return this.material;
    }

    public void setMaterial(String material) {
        this.material = material;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RefWeldProcedures)) return false;
        final RefWeldProcedures refWeldProcedures = (RefWeldProcedures) o;
        return Objects.equals(getId(), refWeldProcedures.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

