/*Copyright (c) 2016-2018 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.job1111;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Settings generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`SETTINGS`")
public class Settings implements Serializable {

    private String label;
    private Float value1;
    private String value2;

    @Id
    @Column(name = "`Label`", nullable = false, length = 32)
    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    @Column(name = "`Value1`", nullable = true, scale = 3, precision = 6)
    public Float getValue1() {
        return this.value1;
    }

    public void setValue1(Float value1) {
        this.value1 = value1;
    }

    @Column(name = "`Value2`", nullable = true, length = 45)
    public String getValue2() {
        return this.value2;
    }

    public void setValue2(String value2) {
        this.value2 = value2;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Settings)) return false;
        final Settings settings = (Settings) o;
        return Objects.equals(getLabel(), settings.getLabel());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getLabel());
    }
}

