/*Copyright (c) 2016-2017 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.job1111;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * SubsBoltUp generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`SubsBoltUp`")
public class SubsBoltUp implements Serializable {

    private Integer id;
    private int fkSubmissionId;
    private String boltUpSpool1;
    private String boltUpSpool2;
    private String boltUpDrawingNumber;
    private String boltUpLineNumber;
    private String boltUpSheetNumber;
    private Short boltUpTimeInForm;
    private Float boltUpSize;
    private Short boltUpQuantity;
    private Short boltUpRework;
    private String boltUpNotes;
    private Short activityType;
    private short rev;
    private Timestamp timeStamp;
    private SubsDetails subsDetails;
    private List<SubsBoltUpRev> subsBoltUpRevs;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`fk_SubmissionId`", nullable = false, scale = 0, precision = 10)
    public int getFkSubmissionId() {
        return this.fkSubmissionId;
    }

    public void setFkSubmissionId(int fkSubmissionId) {
        this.fkSubmissionId = fkSubmissionId;
    }

    @Column(name = "`BoltUpSpool1`", nullable = true, length = 45)
    public String getBoltUpSpool1() {
        return this.boltUpSpool1;
    }

    public void setBoltUpSpool1(String boltUpSpool1) {
        this.boltUpSpool1 = boltUpSpool1;
    }

    @Column(name = "`BoltUpSpool2`", nullable = true, length = 45)
    public String getBoltUpSpool2() {
        return this.boltUpSpool2;
    }

    public void setBoltUpSpool2(String boltUpSpool2) {
        this.boltUpSpool2 = boltUpSpool2;
    }

    @Column(name = "`BoltUpDrawingNumber`", nullable = true, length = 45)
    public String getBoltUpDrawingNumber() {
        return this.boltUpDrawingNumber;
    }

    public void setBoltUpDrawingNumber(String boltUpDrawingNumber) {
        this.boltUpDrawingNumber = boltUpDrawingNumber;
    }

    @Column(name = "`BoltUpLineNumber`", nullable = true, length = 45)
    public String getBoltUpLineNumber() {
        return this.boltUpLineNumber;
    }

    public void setBoltUpLineNumber(String boltUpLineNumber) {
        this.boltUpLineNumber = boltUpLineNumber;
    }

    @Column(name = "`BoltUpSheetNumber`", nullable = true, length = 3)
    public String getBoltUpSheetNumber() {
        return this.boltUpSheetNumber;
    }

    public void setBoltUpSheetNumber(String boltUpSheetNumber) {
        this.boltUpSheetNumber = boltUpSheetNumber;
    }

    @Column(name = "`BoltUpTimeInForm`", nullable = true, scale = 0, precision = 5)
    public Short getBoltUpTimeInForm() {
        return this.boltUpTimeInForm;
    }

    public void setBoltUpTimeInForm(Short boltUpTimeInForm) {
        this.boltUpTimeInForm = boltUpTimeInForm;
    }

    @Column(name = "`BoltUpSize`", nullable = true, scale = 2, precision = 5)
    public Float getBoltUpSize() {
        return this.boltUpSize;
    }

    public void setBoltUpSize(Float boltUpSize) {
        this.boltUpSize = boltUpSize;
    }

    @Column(name = "`BoltUpQuantity`", nullable = true, scale = 0, precision = 3)
    public Short getBoltUpQuantity() {
        return this.boltUpQuantity;
    }

    public void setBoltUpQuantity(Short boltUpQuantity) {
        this.boltUpQuantity = boltUpQuantity;
    }

    @Column(name = "`BoltUpRework`", nullable = true, scale = 0, precision = 3)
    public Short getBoltUpRework() {
        return this.boltUpRework;
    }

    public void setBoltUpRework(Short boltUpRework) {
        this.boltUpRework = boltUpRework;
    }

    @Column(name = "`BoltUpNotes`", nullable = true, length = 255)
    public String getBoltUpNotes() {
        return this.boltUpNotes;
    }

    public void setBoltUpNotes(String boltUpNotes) {
        this.boltUpNotes = boltUpNotes;
    }

    @Column(name = "`ActivityType`", nullable = true, scale = 0, precision = 3)
    public Short getActivityType() {
        return this.activityType;
    }

    public void setActivityType(Short activityType) {
        this.activityType = activityType;
    }

    @Column(name = "`Rev`", nullable = false, scale = 0, precision = 3)
    public short getRev() {
        return this.rev;
    }

    public void setRev(short rev) {
        this.rev = rev;
    }

    @Column(name = "`TimeStamp`", nullable = true)
    public Timestamp getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Timestamp timeStamp) {
        this.timeStamp = timeStamp;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`fk_SubmissionId`", referencedColumnName = "`SubmissionID`", insertable = false, updatable = false)
    public SubsDetails getSubsDetails() {
        return this.subsDetails;
    }

    public void setSubsDetails(SubsDetails subsDetails) {
        if(subsDetails != null) {
            this.fkSubmissionId = subsDetails.getSubmissionId();
        }

        this.subsDetails = subsDetails;
    }

    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "subsBoltUp")
    public List<SubsBoltUpRev> getSubsBoltUpRevs() {
        return this.subsBoltUpRevs;
    }

    public void setSubsBoltUpRevs(List<SubsBoltUpRev> subsBoltUpRevs) {
        this.subsBoltUpRevs = subsBoltUpRevs;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SubsBoltUp)) return false;
        final SubsBoltUp subsBoltUp = (SubsBoltUp) o;
        return Objects.equals(getId(), subsBoltUp.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

