/*Copyright (c) 2016-2017 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.psa.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class InsertLoginFailureRequest implements Serializable {

    @JsonProperty("EnteredUsername")
    private String enteredUsername;
    @JsonProperty("EnteredPassword")
    private String enteredPassword;

    public String getEnteredUsername() {
        return this.enteredUsername;
    }

    public void setEnteredUsername(String enteredUsername) {
        this.enteredUsername = enteredUsername;
    }

    public String getEnteredPassword() {
        return this.enteredPassword;
    }

    public void setEnteredPassword(String enteredPassword) {
        this.enteredPassword = enteredPassword;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof InsertLoginFailureRequest)) return false;
        final InsertLoginFailureRequest insertLoginFailureRequest = (InsertLoginFailureRequest) o;
        return Objects.equals(getEnteredUsername(), insertLoginFailureRequest.getEnteredUsername()) &&
                Objects.equals(getEnteredPassword(), insertLoginFailureRequest.getEnteredPassword());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEnteredUsername(),
                getEnteredPassword());
    }
}
