/*Copyright (c) 2016-2018 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.psa.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class InsertChatMessageRequest implements Serializable {


    @JsonProperty("ConversationID")
    private Integer conversationId;

    @JsonProperty("UserID")
    private Integer userId;

    @JsonProperty("Message")
    private String message;

    public Integer getConversationId() {
        return this.conversationId;
    }

    public void setConversationId(Integer conversationId) {
        this.conversationId = conversationId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof InsertChatMessageRequest)) return false;
        final InsertChatMessageRequest insertChatMessageRequest = (InsertChatMessageRequest) o;
        return Objects.equals(getConversationId(), insertChatMessageRequest.getConversationId()) &&
                Objects.equals(getUserId(), insertChatMessageRequest.getUserId()) &&
                Objects.equals(getMessage(), insertChatMessageRequest.getMessage());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getConversationId(),
                getUserId(),
                getMessage());
    }
}
