/*Copyright (c) 2016-2017 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.job1111.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.psabackoffice.job1111.CivilSellPackageRev;

/**
 * Service object for domain model class {@link CivilSellPackageRev}.
 */
public interface CivilSellPackageRevService {

    /**
     * Creates a new CivilSellPackageRev. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on CivilSellPackageRev if any.
     *
     * @param civilSellPackageRev Details of the CivilSellPackageRev to be created; value cannot be null.
     * @return The newly created CivilSellPackageRev.
     */
	CivilSellPackageRev create(CivilSellPackageRev civilSellPackageRev);


	/**
	 * Returns CivilSellPackageRev by given id if exists.
	 *
	 * @param civilsellpackagerevId The id of the CivilSellPackageRev to get; value cannot be null.
	 * @return CivilSellPackageRev associated with the given civilsellpackagerevId.
     * @throws EntityNotFoundException If no CivilSellPackageRev is found.
	 */
	CivilSellPackageRev getById(Integer civilsellpackagerevId) throws EntityNotFoundException;

    /**
	 * Find and return the CivilSellPackageRev by given id if exists, returns null otherwise.
	 *
	 * @param civilsellpackagerevId The id of the CivilSellPackageRev to get; value cannot be null.
	 * @return CivilSellPackageRev associated with the given civilsellpackagerevId.
	 */
	CivilSellPackageRev findById(Integer civilsellpackagerevId);


	/**
	 * Updates the details of an existing CivilSellPackageRev. It replaces all fields of the existing CivilSellPackageRev with the given civilSellPackageRev.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on CivilSellPackageRev if any.
     *
	 * @param civilSellPackageRev The details of the CivilSellPackageRev to be updated; value cannot be null.
	 * @return The updated CivilSellPackageRev.
	 * @throws EntityNotFoundException if no CivilSellPackageRev is found with given input.
	 */
	CivilSellPackageRev update(CivilSellPackageRev civilSellPackageRev) throws EntityNotFoundException;

    /**
	 * Deletes an existing CivilSellPackageRev with the given id.
	 *
	 * @param civilsellpackagerevId The id of the CivilSellPackageRev to be deleted; value cannot be null.
	 * @return The deleted CivilSellPackageRev.
	 * @throws EntityNotFoundException if no CivilSellPackageRev found with the given id.
	 */
	CivilSellPackageRev delete(Integer civilsellpackagerevId) throws EntityNotFoundException;

	/**
	 * Find all CivilSellPackageRevs matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching CivilSellPackageRevs.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<CivilSellPackageRev> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all CivilSellPackageRevs matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching CivilSellPackageRevs.
     *
     * @see Pageable
     * @see Page
	 */
    Page<CivilSellPackageRev> findAll(String query, Pageable pageable);

    /**
	 * Exports all CivilSellPackageRevs matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the CivilSellPackageRevs in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the CivilSellPackageRev.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

