/*Copyright (c) 2016-2017 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.job1111.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.psabackoffice.job1111.EquipTrackerDetailsRev;

/**
 * Service object for domain model class {@link EquipTrackerDetailsRev}.
 */
public interface EquipTrackerDetailsRevService {

    /**
     * Creates a new EquipTrackerDetailsRev. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on EquipTrackerDetailsRev if any.
     *
     * @param equipTrackerDetailsRev Details of the EquipTrackerDetailsRev to be created; value cannot be null.
     * @return The newly created EquipTrackerDetailsRev.
     */
	EquipTrackerDetailsRev create(EquipTrackerDetailsRev equipTrackerDetailsRev);


	/**
	 * Returns EquipTrackerDetailsRev by given id if exists.
	 *
	 * @param equiptrackerdetailsrevId The id of the EquipTrackerDetailsRev to get; value cannot be null.
	 * @return EquipTrackerDetailsRev associated with the given equiptrackerdetailsrevId.
     * @throws EntityNotFoundException If no EquipTrackerDetailsRev is found.
	 */
	EquipTrackerDetailsRev getById(Integer equiptrackerdetailsrevId) throws EntityNotFoundException;

    /**
	 * Find and return the EquipTrackerDetailsRev by given id if exists, returns null otherwise.
	 *
	 * @param equiptrackerdetailsrevId The id of the EquipTrackerDetailsRev to get; value cannot be null.
	 * @return EquipTrackerDetailsRev associated with the given equiptrackerdetailsrevId.
	 */
	EquipTrackerDetailsRev findById(Integer equiptrackerdetailsrevId);


	/**
	 * Updates the details of an existing EquipTrackerDetailsRev. It replaces all fields of the existing EquipTrackerDetailsRev with the given equipTrackerDetailsRev.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on EquipTrackerDetailsRev if any.
     *
	 * @param equipTrackerDetailsRev The details of the EquipTrackerDetailsRev to be updated; value cannot be null.
	 * @return The updated EquipTrackerDetailsRev.
	 * @throws EntityNotFoundException if no EquipTrackerDetailsRev is found with given input.
	 */
	EquipTrackerDetailsRev update(EquipTrackerDetailsRev equipTrackerDetailsRev) throws EntityNotFoundException;

    /**
	 * Deletes an existing EquipTrackerDetailsRev with the given id.
	 *
	 * @param equiptrackerdetailsrevId The id of the EquipTrackerDetailsRev to be deleted; value cannot be null.
	 * @return The deleted EquipTrackerDetailsRev.
	 * @throws EntityNotFoundException if no EquipTrackerDetailsRev found with the given id.
	 */
	EquipTrackerDetailsRev delete(Integer equiptrackerdetailsrevId) throws EntityNotFoundException;

	/**
	 * Find all EquipTrackerDetailsRevs matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching EquipTrackerDetailsRevs.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<EquipTrackerDetailsRev> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all EquipTrackerDetailsRevs matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching EquipTrackerDetailsRevs.
     *
     * @see Pageable
     * @see Page
	 */
    Page<EquipTrackerDetailsRev> findAll(String query, Pageable pageable);

    /**
	 * Exports all EquipTrackerDetailsRevs matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the EquipTrackerDetailsRevs in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the EquipTrackerDetailsRev.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

