/*Copyright (c) 2016-2017 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.job1111.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.psabackoffice.job1111.PipeTrim;


/**
 * ServiceImpl object for domain model class PipeTrim.
 *
 * @see PipeTrim
 */
@Service("Job1111.PipeTrimService")
@Validated
public class PipeTrimServiceImpl implements PipeTrimService {

    private static final Logger LOGGER = LoggerFactory.getLogger(PipeTrimServiceImpl.class);


    @Autowired
    @Qualifier("Job1111.PipeTrimDao")
    private WMGenericDao<PipeTrim, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<PipeTrim, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "Job1111TransactionManager")
    @Override
	public PipeTrim create(PipeTrim pipeTrim) {
        LOGGER.debug("Creating a new PipeTrim with information: {}", pipeTrim);

        PipeTrim pipeTrimCreated = this.wmGenericDao.create(pipeTrim);
        return pipeTrimCreated;
    }

	@Transactional(readOnly = true, value = "Job1111TransactionManager")
	@Override
	public PipeTrim getById(Integer pipetrimId) throws EntityNotFoundException {
        LOGGER.debug("Finding PipeTrim by id: {}", pipetrimId);
        PipeTrim pipeTrim = this.wmGenericDao.findById(pipetrimId);
        if (pipeTrim == null){
            LOGGER.debug("No PipeTrim found with id: {}", pipetrimId);
            throw new EntityNotFoundException(String.valueOf(pipetrimId));
        }
        return pipeTrim;
    }

    @Transactional(readOnly = true, value = "Job1111TransactionManager")
	@Override
	public PipeTrim findById(Integer pipetrimId) {
        LOGGER.debug("Finding PipeTrim by id: {}", pipetrimId);
        return this.wmGenericDao.findById(pipetrimId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "Job1111TransactionManager")
	@Override
	public PipeTrim update(PipeTrim pipeTrim) throws EntityNotFoundException {
        LOGGER.debug("Updating PipeTrim with information: {}", pipeTrim);
        this.wmGenericDao.update(pipeTrim);

        Integer pipetrimId = pipeTrim.getId();

        return this.wmGenericDao.findById(pipetrimId);
    }

    @Transactional(value = "Job1111TransactionManager")
	@Override
	public PipeTrim delete(Integer pipetrimId) throws EntityNotFoundException {
        LOGGER.debug("Deleting PipeTrim with id: {}", pipetrimId);
        PipeTrim deleted = this.wmGenericDao.findById(pipetrimId);
        if (deleted == null) {
            LOGGER.debug("No PipeTrim found with id: {}", pipetrimId);
            throw new EntityNotFoundException(String.valueOf(pipetrimId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "Job1111TransactionManager")
	@Override
	public Page<PipeTrim> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all PipeTrims");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "Job1111TransactionManager")
    @Override
    public Page<PipeTrim> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all PipeTrims");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "Job1111TransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service Job1111 for table PipeTrim to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "Job1111TransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "Job1111TransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

