/*Copyright (c) 2016-2018 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.job1111.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.psabackoffice.job1111.PipeTesting;


/**
 * ServiceImpl object for domain model class PipeTesting.
 *
 * @see PipeTesting
 */
@Service("Job1111.PipeTestingService")
@Validated
public class PipeTestingServiceImpl implements PipeTestingService {

    private static final Logger LOGGER = LoggerFactory.getLogger(PipeTestingServiceImpl.class);


    @Autowired
    @Qualifier("Job1111.PipeTestingDao")
    private WMGenericDao<PipeTesting, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<PipeTesting, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "Job1111TransactionManager")
    @Override
	public PipeTesting create(PipeTesting pipeTesting) {
        LOGGER.debug("Creating a new PipeTesting with information: {}", pipeTesting);

        PipeTesting pipeTestingCreated = this.wmGenericDao.create(pipeTesting);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(pipeTestingCreated);
    }

	@Transactional(readOnly = true, value = "Job1111TransactionManager")
	@Override
	public PipeTesting getById(Integer pipetestingId) {
        LOGGER.debug("Finding PipeTesting by id: {}", pipetestingId);
        return this.wmGenericDao.findById(pipetestingId);
    }

    @Transactional(readOnly = true, value = "Job1111TransactionManager")
	@Override
	public PipeTesting findById(Integer pipetestingId) {
        LOGGER.debug("Finding PipeTesting by id: {}", pipetestingId);
        try {
            return this.wmGenericDao.findById(pipetestingId);
        } catch(EntityNotFoundException ex) {
            LOGGER.debug("No PipeTesting found with id: {}", pipetestingId, ex);
            return null;
        }
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "Job1111TransactionManager")
	@Override
	public PipeTesting update(PipeTesting pipeTesting) {
        LOGGER.debug("Updating PipeTesting with information: {}", pipeTesting);

        this.wmGenericDao.update(pipeTesting);
        this.wmGenericDao.refresh(pipeTesting);

        return pipeTesting;
    }

    @Transactional(value = "Job1111TransactionManager")
	@Override
	public PipeTesting delete(Integer pipetestingId) {
        LOGGER.debug("Deleting PipeTesting with id: {}", pipetestingId);
        PipeTesting deleted = this.wmGenericDao.findById(pipetestingId);
        if (deleted == null) {
            LOGGER.debug("No PipeTesting found with id: {}", pipetestingId);
            throw new EntityNotFoundException(String.valueOf(pipetestingId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "Job1111TransactionManager")
	@Override
	public void delete(PipeTesting pipeTesting) {
        LOGGER.debug("Deleting PipeTesting with {}", pipeTesting);
        this.wmGenericDao.delete(pipeTesting);
    }

	@Transactional(readOnly = true, value = "Job1111TransactionManager")
	@Override
	public Page<PipeTesting> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all PipeTestings");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "Job1111TransactionManager")
    @Override
    public Page<PipeTesting> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all PipeTestings");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "Job1111TransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service Job1111 for table PipeTesting to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "Job1111TransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "Job1111TransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

