/*Copyright (c) 2016-2017 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.job1111.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.psabackoffice.job1111.SteelBoltOut;

/**
 * Service object for domain model class {@link SteelBoltOut}.
 */
public interface SteelBoltOutService {

    /**
     * Creates a new SteelBoltOut. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on SteelBoltOut if any.
     *
     * @param steelBoltOut Details of the SteelBoltOut to be created; value cannot be null.
     * @return The newly created SteelBoltOut.
     */
	SteelBoltOut create(SteelBoltOut steelBoltOut);


	/**
	 * Returns SteelBoltOut by given id if exists.
	 *
	 * @param steelboltoutId The id of the SteelBoltOut to get; value cannot be null.
	 * @return SteelBoltOut associated with the given steelboltoutId.
     * @throws EntityNotFoundException If no SteelBoltOut is found.
	 */
	SteelBoltOut getById(Integer steelboltoutId) throws EntityNotFoundException;

    /**
	 * Find and return the SteelBoltOut by given id if exists, returns null otherwise.
	 *
	 * @param steelboltoutId The id of the SteelBoltOut to get; value cannot be null.
	 * @return SteelBoltOut associated with the given steelboltoutId.
	 */
	SteelBoltOut findById(Integer steelboltoutId);


	/**
	 * Updates the details of an existing SteelBoltOut. It replaces all fields of the existing SteelBoltOut with the given steelBoltOut.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on SteelBoltOut if any.
     *
	 * @param steelBoltOut The details of the SteelBoltOut to be updated; value cannot be null.
	 * @return The updated SteelBoltOut.
	 * @throws EntityNotFoundException if no SteelBoltOut is found with given input.
	 */
	SteelBoltOut update(SteelBoltOut steelBoltOut) throws EntityNotFoundException;

    /**
	 * Deletes an existing SteelBoltOut with the given id.
	 *
	 * @param steelboltoutId The id of the SteelBoltOut to be deleted; value cannot be null.
	 * @return The deleted SteelBoltOut.
	 * @throws EntityNotFoundException if no SteelBoltOut found with the given id.
	 */
	SteelBoltOut delete(Integer steelboltoutId) throws EntityNotFoundException;

	/**
	 * Find all SteelBoltOuts matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching SteelBoltOuts.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<SteelBoltOut> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all SteelBoltOuts matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching SteelBoltOuts.
     *
     * @see Pageable
     * @see Page
	 */
    Page<SteelBoltOut> findAll(String query, Pageable pageable);

    /**
	 * Exports all SteelBoltOuts matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the SteelBoltOuts in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the SteelBoltOut.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

