/*Copyright (c) 2016-2017 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.job1111.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.psabackoffice.job1111.SteelFa;

/**
 * Service object for domain model class {@link SteelFa}.
 */
public interface SteelFaService {

    /**
     * Creates a new SteelFa. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on SteelFa if any.
     *
     * @param steelFa Details of the SteelFa to be created; value cannot be null.
     * @return The newly created SteelFa.
     */
	SteelFa create(@Valid SteelFa steelFa);


	/**
	 * Returns SteelFa by given id if exists.
	 *
	 * @param steelfaId The id of the SteelFa to get; value cannot be null.
	 * @return SteelFa associated with the given steelfaId.
     * @throws EntityNotFoundException If no SteelFa is found.
	 */
	SteelFa getById(Integer steelfaId);

    /**
	 * Find and return the SteelFa by given id if exists, returns null otherwise.
	 *
	 * @param steelfaId The id of the SteelFa to get; value cannot be null.
	 * @return SteelFa associated with the given steelfaId.
	 */
	SteelFa findById(Integer steelfaId);


	/**
	 * Updates the details of an existing SteelFa. It replaces all fields of the existing SteelFa with the given steelFa.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on SteelFa if any.
     *
	 * @param steelFa The details of the SteelFa to be updated; value cannot be null.
	 * @return The updated SteelFa.
	 * @throws EntityNotFoundException if no SteelFa is found with given input.
	 */
	SteelFa update(@Valid SteelFa steelFa);

    /**
	 * Deletes an existing SteelFa with the given id.
	 *
	 * @param steelfaId The id of the SteelFa to be deleted; value cannot be null.
	 * @return The deleted SteelFa.
	 * @throws EntityNotFoundException if no SteelFa found with the given id.
	 */
	SteelFa delete(Integer steelfaId);

    /**
	 * Deletes an existing SteelFa with the given object.
	 *
	 * @param steelFa The instance of the SteelFa to be deleted; value cannot be null.
	 */
	void delete(SteelFa steelFa);

	/**
	 * Find all SteelFas matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching SteelFas.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<SteelFa> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all SteelFas matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching SteelFas.
     *
     * @see Pageable
     * @see Page
	 */
    Page<SteelFa> findAll(String query, Pageable pageable);

    /**
	 * Exports all SteelFas matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the SteelFas in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the SteelFa.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

