/*Copyright (c) 2016-2017 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.job1111.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.psabackoffice.job1111.SubsSignatures;


/**
 * ServiceImpl object for domain model class SubsSignatures.
 *
 * @see SubsSignatures
 */
@Service("Job1111.SubsSignaturesService")
public class SubsSignaturesServiceImpl implements SubsSignaturesService {

    private static final Logger LOGGER = LoggerFactory.getLogger(SubsSignaturesServiceImpl.class);


    @Autowired
    @Qualifier("Job1111.SubsSignaturesDao")
    private WMGenericDao<SubsSignatures, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<SubsSignatures, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "Job1111TransactionManager")
    @Override
	public SubsSignatures create(SubsSignatures subsSignatures) {
        LOGGER.debug("Creating a new SubsSignatures with information: {}", subsSignatures);
        SubsSignatures subsSignaturesCreated = this.wmGenericDao.create(subsSignatures);
        return subsSignaturesCreated;
    }

	@Transactional(readOnly = true, value = "Job1111TransactionManager")
	@Override
	public SubsSignatures getById(Integer subssignaturesId) throws EntityNotFoundException {
        LOGGER.debug("Finding SubsSignatures by id: {}", subssignaturesId);
        SubsSignatures subsSignatures = this.wmGenericDao.findById(subssignaturesId);
        if (subsSignatures == null){
            LOGGER.debug("No SubsSignatures found with id: {}", subssignaturesId);
            throw new EntityNotFoundException(String.valueOf(subssignaturesId));
        }
        return subsSignatures;
    }

    @Transactional(readOnly = true, value = "Job1111TransactionManager")
	@Override
	public SubsSignatures findById(Integer subssignaturesId) {
        LOGGER.debug("Finding SubsSignatures by id: {}", subssignaturesId);
        return this.wmGenericDao.findById(subssignaturesId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "Job1111TransactionManager")
	@Override
	public SubsSignatures update(SubsSignatures subsSignatures) throws EntityNotFoundException {
        LOGGER.debug("Updating SubsSignatures with information: {}", subsSignatures);
        this.wmGenericDao.update(subsSignatures);

        Integer subssignaturesId = subsSignatures.getId();

        return this.wmGenericDao.findById(subssignaturesId);
    }

    @Transactional(value = "Job1111TransactionManager")
	@Override
	public SubsSignatures delete(Integer subssignaturesId) throws EntityNotFoundException {
        LOGGER.debug("Deleting SubsSignatures with id: {}", subssignaturesId);
        SubsSignatures deleted = this.wmGenericDao.findById(subssignaturesId);
        if (deleted == null) {
            LOGGER.debug("No SubsSignatures found with id: {}", subssignaturesId);
            throw new EntityNotFoundException(String.valueOf(subssignaturesId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "Job1111TransactionManager")
	@Override
	public Page<SubsSignatures> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all SubsSignatures");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "Job1111TransactionManager")
    @Override
    public Page<SubsSignatures> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all SubsSignatures");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "Job1111TransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service Job1111 for table SubsSignatures to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "Job1111TransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "Job1111TransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

