/*Copyright (c) 2016-2018 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.psa;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RefActivityRejections generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`REF_ActivityRejections`")
public class RefActivityRejections implements Serializable {

    private Integer id;
    private String label;

    @Id
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 3)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`Label`", nullable = true, length = 90)
    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RefActivityRejections)) return false;
        final RefActivityRejections refActivityRejections = (RefActivityRejections) o;
        return Objects.equals(getId(), refActivityRejections.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

