/*Copyright (c) 2016-2018 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.psa;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RefPercentList generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`REF_PercentList`")
public class RefPercentList implements Serializable {

    private Integer id;
    private String label;
    private Short value;
    private Float decimalValue;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`Label`", nullable = true, length = 4)
    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    @Column(name = "`Value`", nullable = true, scale = 0, precision = 3)
    public Short getValue() {
        return this.value;
    }

    public void setValue(Short value) {
        this.value = value;
    }

    @Column(name = "`DecimalValue`", nullable = true, scale = 2, precision = 3)
    public Float getDecimalValue() {
        return this.decimalValue;
    }

    public void setDecimalValue(Float decimalValue) {
        this.decimalValue = decimalValue;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RefPercentList)) return false;
        final RefPercentList refPercentList = (RefPercentList) o;
        return Objects.equals(getId(), refPercentList.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

