/*Copyright (c) 2016-2017 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.psa.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.psabackoffice.psa.TblUserCreds;

/**
 * Service object for domain model class {@link TblUserCreds}.
 */
public interface TblUserCredsService {

    /**
     * Creates a new TblUserCreds. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on TblUserCreds if any.
     *
     * @param tblUserCreds Details of the TblUserCreds to be created; value cannot be null.
     * @return The newly created TblUserCreds.
     */
	TblUserCreds create(@Valid TblUserCreds tblUserCreds);


	/**
	 * Returns TblUserCreds by given id if exists.
	 *
	 * @param tblusercredsId The id of the TblUserCreds to get; value cannot be null.
	 * @return TblUserCreds associated with the given tblusercredsId.
     * @throws EntityNotFoundException If no TblUserCreds is found.
	 */
	TblUserCreds getById(Integer tblusercredsId) throws EntityNotFoundException;

    /**
	 * Find and return the TblUserCreds by given id if exists, returns null otherwise.
	 *
	 * @param tblusercredsId The id of the TblUserCreds to get; value cannot be null.
	 * @return TblUserCreds associated with the given tblusercredsId.
	 */
	TblUserCreds findById(Integer tblusercredsId);


	/**
	 * Updates the details of an existing TblUserCreds. It replaces all fields of the existing TblUserCreds with the given tblUserCreds.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on TblUserCreds if any.
     *
	 * @param tblUserCreds The details of the TblUserCreds to be updated; value cannot be null.
	 * @return The updated TblUserCreds.
	 * @throws EntityNotFoundException if no TblUserCreds is found with given input.
	 */
	TblUserCreds update(@Valid TblUserCreds tblUserCreds) throws EntityNotFoundException;

    /**
	 * Deletes an existing TblUserCreds with the given id.
	 *
	 * @param tblusercredsId The id of the TblUserCreds to be deleted; value cannot be null.
	 * @return The deleted TblUserCreds.
	 * @throws EntityNotFoundException if no TblUserCreds found with the given id.
	 */
	TblUserCreds delete(Integer tblusercredsId) throws EntityNotFoundException;

	/**
	 * Find all TblUserCreds matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching TblUserCreds.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<TblUserCreds> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all TblUserCreds matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching TblUserCreds.
     *
     * @see Pageable
     * @see Page
	 */
    Page<TblUserCreds> findAll(String query, Pageable pageable);

    /**
	 * Exports all TblUserCreds matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the TblUserCreds in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the TblUserCreds.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

