/*Copyright (c) 2016-2017 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.psa.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.psabackoffice.psa.TblUserCreds;


/**
 * ServiceImpl object for domain model class TblUserCreds.
 *
 * @see TblUserCreds
 */
@Service("PSA.TblUserCredsService")
@Validated
public class TblUserCredsServiceImpl implements TblUserCredsService {

    private static final Logger LOGGER = LoggerFactory.getLogger(TblUserCredsServiceImpl.class);


    @Autowired
    @Qualifier("PSA.TblUserCredsDao")
    private WMGenericDao<TblUserCreds, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<TblUserCreds, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "PSATransactionManager")
    @Override
	public TblUserCreds create(TblUserCreds tblUserCreds) {
        LOGGER.debug("Creating a new TblUserCreds with information: {}", tblUserCreds);

        TblUserCreds tblUserCredsCreated = this.wmGenericDao.create(tblUserCreds);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(tblUserCredsCreated);
    }

	@Transactional(readOnly = true, value = "PSATransactionManager")
	@Override
	public TblUserCreds getById(Integer tblusercredsId) throws EntityNotFoundException {
        LOGGER.debug("Finding TblUserCreds by id: {}", tblusercredsId);
        return this.wmGenericDao.findById(tblusercredsId);
    }

    @Transactional(readOnly = true, value = "PSATransactionManager")
	@Override
	public TblUserCreds findById(Integer tblusercredsId) {
        LOGGER.debug("Finding TblUserCreds by id: {}", tblusercredsId);
        try {
            return this.wmGenericDao.findById(tblusercredsId);
        } catch(EntityNotFoundException ex) {
            LOGGER.debug("No TblUserCreds found with id: {}", tblusercredsId, ex);
            return null;
        }
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "PSATransactionManager")
	@Override
	public TblUserCreds update(TblUserCreds tblUserCreds) throws EntityNotFoundException {
        LOGGER.debug("Updating TblUserCreds with information: {}", tblUserCreds);

        this.wmGenericDao.update(tblUserCreds);
        this.wmGenericDao.refresh(tblUserCreds);

        return tblUserCreds;
    }

    @Transactional(value = "PSATransactionManager")
	@Override
	public TblUserCreds delete(Integer tblusercredsId) throws EntityNotFoundException {
        LOGGER.debug("Deleting TblUserCreds with id: {}", tblusercredsId);
        TblUserCreds deleted = this.wmGenericDao.findById(tblusercredsId);
        if (deleted == null) {
            LOGGER.debug("No TblUserCreds found with id: {}", tblusercredsId);
            throw new EntityNotFoundException(String.valueOf(tblusercredsId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "PSATransactionManager")
	@Override
	public void delete(TblUserCreds tblUserCreds) {
        LOGGER.debug("Deleting TblUserCreds with {}", tblUserCreds);
        this.wmGenericDao.delete(tblUserCreds);
    }

	@Transactional(readOnly = true, value = "PSATransactionManager")
	@Override
	public Page<TblUserCreds> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all TblUserCreds");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "PSATransactionManager")
    @Override
    public Page<TblUserCreds> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all TblUserCreds");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "PSATransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service PSA for table TblUserCreds to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "PSATransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "PSATransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

