/*Copyright (c) 2016-2017 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.job1111.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateSsnoteRequest implements Serializable {


    @JsonProperty("ActivityID")
    @NotNull
    private Integer activityId;

    @JsonProperty("CreatedBy")
    @NotNull
    private Integer createdBy;

    @JsonProperty("Note")
    @NotNull
    private String note;

    public Integer getActivityId() {
        return this.activityId;
    }

    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CreateSsnoteRequest)) return false;
        final CreateSsnoteRequest createSsnoteRequest = (CreateSsnoteRequest) o;
        return Objects.equals(getActivityId(), createSsnoteRequest.getActivityId()) &&
                Objects.equals(getCreatedBy(), createSsnoteRequest.getCreatedBy()) &&
                Objects.equals(getNote(), createSsnoteRequest.getNote());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getActivityId(),
                getCreatedBy(),
                getNote());
    }
}
