/*Copyright (c) 2016-2017 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.job1111.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Timestamp;
import java.util.Objects;

import org.joda.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetBidActivityQuantityResponse implements Serializable {

    @JsonProperty("EstimatedHours")
    @ColumnAlias("EstimatedHours")
    private BigDecimal estimatedHours;
    @JsonProperty("QuantityUnit")
    @ColumnAlias("QuantityUnit")
    private String quantityUnit;
    @JsonProperty("TakeOffQuantity")
    @ColumnAlias("TakeOffQuantity")
    private BigDecimal takeOffQuantity;

    public BigDecimal getEstimatedHours() {
        return this.estimatedHours;
    }

    public void setEstimatedHours(BigDecimal estimatedHours) {
        this.estimatedHours = estimatedHours;
    }

    public String getQuantityUnit() {
        return this.quantityUnit;
    }

    public void setQuantityUnit(String quantityUnit) {
        this.quantityUnit = quantityUnit;
    }

    public BigDecimal getTakeOffQuantity() {
        return this.takeOffQuantity;
    }

    public void setTakeOffQuantity(BigDecimal takeOffQuantity) {
        this.takeOffQuantity = takeOffQuantity;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetBidActivityQuantityResponse)) return false;
        final GetBidActivityQuantityResponse getBidActivityQuantityResponse = (GetBidActivityQuantityResponse) o;
        return Objects.equals(getEstimatedHours(), getBidActivityQuantityResponse.getEstimatedHours()) &&
                Objects.equals(getQuantityUnit(), getBidActivityQuantityResponse.getQuantityUnit()) &&
                Objects.equals(getTakeOffQuantity(), getBidActivityQuantityResponse.getTakeOffQuantity());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEstimatedHours(),
                getQuantityUnit(),
                getTakeOffQuantity());
    }
}
