/*Copyright (c) 2016-2018 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.job1111.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetReportDprequipResponse implements Serializable {


    @ColumnAlias("ActivityID")
    private Integer activityId;

    @ColumnAlias("ActivityTypeID")
    private Short activityTypeId;

    @ColumnAlias("ActivityTypeName")
    private String activityTypeName;

    @ColumnAlias("TagNumber")
    private String tagNumber;

    @ColumnAlias("Description")
    private String description;

    @ColumnAlias("QuantityInstalled")
    private String quantityInstalled;

    @ColumnAlias("CurrentStatus")
    private String currentStatus;

    @ColumnAlias("Rework")
    private Short rework;

    @ColumnAlias("Notes")
    private String notes;

    @ColumnAlias("DateSubmitted")
    private Date dateSubmitted;

    public Integer getActivityId() {
        return this.activityId;
    }

    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    public Short getActivityTypeId() {
        return this.activityTypeId;
    }

    public void setActivityTypeId(Short activityTypeId) {
        this.activityTypeId = activityTypeId;
    }

    public String getActivityTypeName() {
        return this.activityTypeName;
    }

    public void setActivityTypeName(String activityTypeName) {
        this.activityTypeName = activityTypeName;
    }

    public String getTagNumber() {
        return this.tagNumber;
    }

    public void setTagNumber(String tagNumber) {
        this.tagNumber = tagNumber;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getQuantityInstalled() {
        return this.quantityInstalled;
    }

    public void setQuantityInstalled(String quantityInstalled) {
        this.quantityInstalled = quantityInstalled;
    }

    public String getCurrentStatus() {
        return this.currentStatus;
    }

    public void setCurrentStatus(String currentStatus) {
        this.currentStatus = currentStatus;
    }

    public Short getRework() {
        return this.rework;
    }

    public void setRework(Short rework) {
        this.rework = rework;
    }

    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Date getDateSubmitted() {
        return this.dateSubmitted;
    }

    public void setDateSubmitted(Date dateSubmitted) {
        this.dateSubmitted = dateSubmitted;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetReportDprequipResponse)) return false;
        final GetReportDprequipResponse getReportDprequipResponse = (GetReportDprequipResponse) o;
        return Objects.equals(getActivityId(), getReportDprequipResponse.getActivityId()) &&
                Objects.equals(getActivityTypeId(), getReportDprequipResponse.getActivityTypeId()) &&
                Objects.equals(getActivityTypeName(), getReportDprequipResponse.getActivityTypeName()) &&
                Objects.equals(getTagNumber(), getReportDprequipResponse.getTagNumber()) &&
                Objects.equals(getDescription(), getReportDprequipResponse.getDescription()) &&
                Objects.equals(getQuantityInstalled(), getReportDprequipResponse.getQuantityInstalled()) &&
                Objects.equals(getCurrentStatus(), getReportDprequipResponse.getCurrentStatus()) &&
                Objects.equals(getRework(), getReportDprequipResponse.getRework()) &&
                Objects.equals(getNotes(), getReportDprequipResponse.getNotes()) &&
                Objects.equals(getDateSubmitted(), getReportDprequipResponse.getDateSubmitted());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getActivityId(),
                getActivityTypeId(),
                getActivityTypeName(),
                getTagNumber(),
                getDescription(),
                getQuantityInstalled(),
                getCurrentStatus(),
                getRework(),
                getNotes(),
                getDateSubmitted());
    }
}
