/*Copyright (c) 2016-2017 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.job1111.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetSuperRecentActivitesResponse implements Serializable {


    @JsonProperty("ActivityID")
    @ColumnAlias("ActivityID")
    private Integer activityId;

    @JsonProperty("ActivityType")
    @ColumnAlias("ActivityType")
    private String activityType;

    @JsonProperty("Status")
    @ColumnAlias("Status")
    private String status;

    @JsonProperty("TimeStamp")
    @ColumnAlias("TimeStamp")
    private Timestamp timeStamp;

    public Integer getActivityId() {
        return this.activityId;
    }

    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    public String getActivityType() {
        return this.activityType;
    }

    public void setActivityType(String activityType) {
        this.activityType = activityType;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Timestamp getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Timestamp timeStamp) {
        this.timeStamp = timeStamp;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetSuperRecentActivitesResponse)) return false;
        final GetSuperRecentActivitesResponse getSuperRecentActivitesResponse = (GetSuperRecentActivitesResponse) o;
        return Objects.equals(getActivityId(), getSuperRecentActivitesResponse.getActivityId()) &&
                Objects.equals(getActivityType(), getSuperRecentActivitesResponse.getActivityType()) &&
                Objects.equals(getStatus(), getSuperRecentActivitesResponse.getStatus()) &&
                Objects.equals(getTimeStamp(), getSuperRecentActivitesResponse.getTimeStamp());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getActivityId(),
                getActivityType(),
                getStatus(),
                getTimeStamp());
    }
}
