/*Copyright (c) 2016-2018 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.job1111.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateSteelDemoRequest implements Serializable {


    @JsonProperty("BidID")
    @NotNull
    private Integer bidId;

    @JsonProperty("Percentcompleted")
    @NotNull
    private BigDecimal percentcompleted;

    @JsonProperty("Notes")
    private String notes;

    @JsonProperty("ActivityID")
    @NotNull
    private Integer activityId;

    public Integer getBidId() {
        return this.bidId;
    }

    public void setBidId(Integer bidId) {
        this.bidId = bidId;
    }

    public BigDecimal getPercentcompleted() {
        return this.percentcompleted;
    }

    public void setPercentcompleted(BigDecimal percentcompleted) {
        this.percentcompleted = percentcompleted;
    }

    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Integer getActivityId() {
        return this.activityId;
    }

    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UpdateSteelDemoRequest)) return false;
        final UpdateSteelDemoRequest updateSteelDemoRequest = (UpdateSteelDemoRequest) o;
        return Objects.equals(getBidId(), updateSteelDemoRequest.getBidId()) &&
                Objects.equals(getPercentcompleted(), updateSteelDemoRequest.getPercentcompleted()) &&
                Objects.equals(getNotes(), updateSteelDemoRequest.getNotes()) &&
                Objects.equals(getActivityId(), updateSteelDemoRequest.getActivityId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getBidId(),
                getPercentcompleted(),
                getNotes(),
                getActivityId());
    }
}
