/*Copyright (c) 2016-2017 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.psa.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateNewJobSeedsRequest implements Serializable {


    @JsonProperty("jobNumber")
    @NotNull
    private Integer jobNumber;

    public Integer getJobNumber() {
        return this.jobNumber;
    }

    public void setJobNumber(Integer jobNumber) {
        this.jobNumber = jobNumber;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CreateNewJobSeedsRequest)) return false;
        final CreateNewJobSeedsRequest createNewJobSeedsRequest = (CreateNewJobSeedsRequest) o;
        return Objects.equals(getJobNumber(), createNewJobSeedsRequest.getJobNumber());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getJobNumber());
    }
}
