/*Copyright (c) 2016-2017 performance-contractors.com All Rights Reserved.
 This software is the confidential and proprietary information of performance-contractors.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with performance-contractors.com*/
package com.psabackoffice.job1111.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetEquipStatsResponseContent implements Serializable {


    @ColumnAlias("BidID")
    private Integer bidId;

    @ColumnAlias("ProjectServicesRep")
    private String projectServicesRep;

    @ColumnAlias("Scope")
    private String scope;

    @ColumnAlias("Phase")
    private String phase;

    @ColumnAlias("Stage")
    private String stage;

    @ColumnAlias("TestPackageNumber")
    private String testPackageNumber;

    @ColumnAlias("WorkPackage")
    private String workPackage;

    @ColumnAlias("CostCode")
    private String costCode;

    @ColumnAlias("P6ID")
    private String p6id;

    @ColumnAlias("P6Description")
    private String p6description;

    @ColumnAlias("AssignedContractor")
    private String assignedContractor;

    @ColumnAlias("Area")
    private String area;

    @ColumnAlias("Location")
    private String location;

    @ColumnAlias("Structure")
    private String structure;

    @ColumnAlias("CU")
    private String cu;

    @ColumnAlias("Elevation")
    private String elevation;

    @ColumnAlias("System")
    private String system;

    @ColumnAlias("Service")
    private String service;

    @ColumnAlias("EquipmentType")
    private String equipmentType;

    @ColumnAlias("ActivityType")
    private String activityType;

    @ColumnAlias("WBS1")
    private String wbs1;

    @ColumnAlias("WBS2")
    private String wbs2;

    @ColumnAlias("WBS3")
    private String wbs3;

    @ColumnAlias("WBS4")
    private String wbs4;

    @ColumnAlias("WBS5")
    private String wbs5;

    @ColumnAlias("WBS6")
    private String wbs6;

    @ColumnAlias("WBS7")
    private String wbs7;

    @ColumnAlias("WBS8")
    private String wbs8;

    @ColumnAlias("WBS9")
    private String wbs9;

    @ColumnAlias("WBS10")
    private String wbs10;

    @ColumnAlias("CountOffload")
    private BigDecimal countOffload;

    @ColumnAlias("CountSet")
    private BigDecimal countSet;

    @ColumnAlias("CountAllign")
    private BigDecimal countAllign;

    @ColumnAlias("CountDemo")
    private BigDecimal countDemo;

    @ColumnAlias("CountMisc")
    private BigDecimal countMisc;

    @ColumnAlias("HoursOffload")
    private BigDecimal hoursOffload;

    @ColumnAlias("HoursSet")
    private BigDecimal hoursSet;

    @ColumnAlias("HoursAllign")
    private BigDecimal hoursAllign;

    @ColumnAlias("HoursDemo")
    private BigDecimal hoursDemo;

    @ColumnAlias("HoursMisc")
    private BigDecimal hoursMisc;

    @ColumnAlias("HoursAll")
    private BigDecimal hoursAll;

    @ColumnAlias("InstalledOffload")
    private BigDecimal installedOffload;

    @ColumnAlias("InstalledSet")
    private BigDecimal installedSet;

    @ColumnAlias("InstalledAllign")
    private BigDecimal installedAllign;

    @ColumnAlias("InstalledDemo")
    private BigDecimal installedDemo;

    @ColumnAlias("InstalledMisc")
    private BigDecimal installedMisc;

    @ColumnAlias("EarnedOffloadHours")
    private BigDecimal earnedOffloadHours;

    @ColumnAlias("EarnedSetHours")
    private BigDecimal earnedSetHours;

    @ColumnAlias("EarnedAllignHours")
    private BigDecimal earnedAllignHours;

    @ColumnAlias("EarnedDemoHours")
    private BigDecimal earnedDemoHours;

    @ColumnAlias("EarnedMiscHours")
    private BigDecimal earnedMiscHours;

    @ColumnAlias("EarnedAllEquipHours")
    private BigDecimal earnedAllEquipHours;

    @ColumnAlias("RemainingOffload")
    private BigDecimal remainingOffload;

    @ColumnAlias("RemainingSet")
    private BigDecimal remainingSet;

    @ColumnAlias("RemainingAllign")
    private BigDecimal remainingAllign;

    @ColumnAlias("RemainingDemo")
    private BigDecimal remainingDemo;

    @ColumnAlias("RemainingMisc")
    private BigDecimal remainingMisc;

    @ColumnAlias("RemainingOffloadHours")
    private BigDecimal remainingOffloadHours;

    @ColumnAlias("RemainingSetHours")
    private BigDecimal remainingSetHours;

    @ColumnAlias("RemainingAllignHours")
    private BigDecimal remainingAllignHours;

    @ColumnAlias("RemainingDemoHours")
    private BigDecimal remainingDemoHours;

    @ColumnAlias("RemainingMiscHours")
    private BigDecimal remainingMiscHours;

    @ColumnAlias("RemainingAllEquipHours")
    private BigDecimal remainingAllEquipHours;

    @ColumnAlias("PercentComplete")
    private BigDecimal percentComplete;

    public Integer getBidId() {
        return this.bidId;
    }

    public void setBidId(Integer bidId) {
        this.bidId = bidId;
    }

    public String getProjectServicesRep() {
        return this.projectServicesRep;
    }

    public void setProjectServicesRep(String projectServicesRep) {
        this.projectServicesRep = projectServicesRep;
    }

    public String getScope() {
        return this.scope;
    }

    public void setScope(String scope) {
        this.scope = scope;
    }

    public String getPhase() {
        return this.phase;
    }

    public void setPhase(String phase) {
        this.phase = phase;
    }

    public String getStage() {
        return this.stage;
    }

    public void setStage(String stage) {
        this.stage = stage;
    }

    public String getTestPackageNumber() {
        return this.testPackageNumber;
    }

    public void setTestPackageNumber(String testPackageNumber) {
        this.testPackageNumber = testPackageNumber;
    }

    public String getWorkPackage() {
        return this.workPackage;
    }

    public void setWorkPackage(String workPackage) {
        this.workPackage = workPackage;
    }

    public String getCostCode() {
        return this.costCode;
    }

    public void setCostCode(String costCode) {
        this.costCode = costCode;
    }

    public String getP6id() {
        return this.p6id;
    }

    public void setP6id(String p6id) {
        this.p6id = p6id;
    }

    public String getP6description() {
        return this.p6description;
    }

    public void setP6description(String p6description) {
        this.p6description = p6description;
    }

    public String getAssignedContractor() {
        return this.assignedContractor;
    }

    public void setAssignedContractor(String assignedContractor) {
        this.assignedContractor = assignedContractor;
    }

    public String getArea() {
        return this.area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getStructure() {
        return this.structure;
    }

    public void setStructure(String structure) {
        this.structure = structure;
    }

    public String getCu() {
        return this.cu;
    }

    public void setCu(String cu) {
        this.cu = cu;
    }

    public String getElevation() {
        return this.elevation;
    }

    public void setElevation(String elevation) {
        this.elevation = elevation;
    }

    public String getSystem() {
        return this.system;
    }

    public void setSystem(String system) {
        this.system = system;
    }

    public String getService() {
        return this.service;
    }

    public void setService(String service) {
        this.service = service;
    }

    public String getEquipmentType() {
        return this.equipmentType;
    }

    public void setEquipmentType(String equipmentType) {
        this.equipmentType = equipmentType;
    }

    public String getActivityType() {
        return this.activityType;
    }

    public void setActivityType(String activityType) {
        this.activityType = activityType;
    }

    public String getWbs1() {
        return this.wbs1;
    }

    public void setWbs1(String wbs1) {
        this.wbs1 = wbs1;
    }

    public String getWbs2() {
        return this.wbs2;
    }

    public void setWbs2(String wbs2) {
        this.wbs2 = wbs2;
    }

    public String getWbs3() {
        return this.wbs3;
    }

    public void setWbs3(String wbs3) {
        this.wbs3 = wbs3;
    }

    public String getWbs4() {
        return this.wbs4;
    }

    public void setWbs4(String wbs4) {
        this.wbs4 = wbs4;
    }

    public String getWbs5() {
        return this.wbs5;
    }

    public void setWbs5(String wbs5) {
        this.wbs5 = wbs5;
    }

    public String getWbs6() {
        return this.wbs6;
    }

    public void setWbs6(String wbs6) {
        this.wbs6 = wbs6;
    }

    public String getWbs7() {
        return this.wbs7;
    }

    public void setWbs7(String wbs7) {
        this.wbs7 = wbs7;
    }

    public String getWbs8() {
        return this.wbs8;
    }

    public void setWbs8(String wbs8) {
        this.wbs8 = wbs8;
    }

    public String getWbs9() {
        return this.wbs9;
    }

    public void setWbs9(String wbs9) {
        this.wbs9 = wbs9;
    }

    public String getWbs10() {
        return this.wbs10;
    }

    public void setWbs10(String wbs10) {
        this.wbs10 = wbs10;
    }

    public BigDecimal getCountOffload() {
        return this.countOffload;
    }

    public void setCountOffload(BigDecimal countOffload) {
        this.countOffload = countOffload;
    }

    public BigDecimal getCountSet() {
        return this.countSet;
    }

    public void setCountSet(BigDecimal countSet) {
        this.countSet = countSet;
    }

    public BigDecimal getCountAllign() {
        return this.countAllign;
    }

    public void setCountAllign(BigDecimal countAllign) {
        this.countAllign = countAllign;
    }

    public BigDecimal getCountDemo() {
        return this.countDemo;
    }

    public void setCountDemo(BigDecimal countDemo) {
        this.countDemo = countDemo;
    }

    public BigDecimal getCountMisc() {
        return this.countMisc;
    }

    public void setCountMisc(BigDecimal countMisc) {
        this.countMisc = countMisc;
    }

    public BigDecimal getHoursOffload() {
        return this.hoursOffload;
    }

    public void setHoursOffload(BigDecimal hoursOffload) {
        this.hoursOffload = hoursOffload;
    }

    public BigDecimal getHoursSet() {
        return this.hoursSet;
    }

    public void setHoursSet(BigDecimal hoursSet) {
        this.hoursSet = hoursSet;
    }

    public BigDecimal getHoursAllign() {
        return this.hoursAllign;
    }

    public void setHoursAllign(BigDecimal hoursAllign) {
        this.hoursAllign = hoursAllign;
    }

    public BigDecimal getHoursDemo() {
        return this.hoursDemo;
    }

    public void setHoursDemo(BigDecimal hoursDemo) {
        this.hoursDemo = hoursDemo;
    }

    public BigDecimal getHoursMisc() {
        return this.hoursMisc;
    }

    public void setHoursMisc(BigDecimal hoursMisc) {
        this.hoursMisc = hoursMisc;
    }

    public BigDecimal getHoursAll() {
        return this.hoursAll;
    }

    public void setHoursAll(BigDecimal hoursAll) {
        this.hoursAll = hoursAll;
    }

    public BigDecimal getInstalledOffload() {
        return this.installedOffload;
    }

    public void setInstalledOffload(BigDecimal installedOffload) {
        this.installedOffload = installedOffload;
    }

    public BigDecimal getInstalledSet() {
        return this.installedSet;
    }

    public void setInstalledSet(BigDecimal installedSet) {
        this.installedSet = installedSet;
    }

    public BigDecimal getInstalledAllign() {
        return this.installedAllign;
    }

    public void setInstalledAllign(BigDecimal installedAllign) {
        this.installedAllign = installedAllign;
    }

    public BigDecimal getInstalledDemo() {
        return this.installedDemo;
    }

    public void setInstalledDemo(BigDecimal installedDemo) {
        this.installedDemo = installedDemo;
    }

    public BigDecimal getInstalledMisc() {
        return this.installedMisc;
    }

    public void setInstalledMisc(BigDecimal installedMisc) {
        this.installedMisc = installedMisc;
    }

    public BigDecimal getEarnedOffloadHours() {
        return this.earnedOffloadHours;
    }

    public void setEarnedOffloadHours(BigDecimal earnedOffloadHours) {
        this.earnedOffloadHours = earnedOffloadHours;
    }

    public BigDecimal getEarnedSetHours() {
        return this.earnedSetHours;
    }

    public void setEarnedSetHours(BigDecimal earnedSetHours) {
        this.earnedSetHours = earnedSetHours;
    }

    public BigDecimal getEarnedAllignHours() {
        return this.earnedAllignHours;
    }

    public void setEarnedAllignHours(BigDecimal earnedAllignHours) {
        this.earnedAllignHours = earnedAllignHours;
    }

    public BigDecimal getEarnedDemoHours() {
        return this.earnedDemoHours;
    }

    public void setEarnedDemoHours(BigDecimal earnedDemoHours) {
        this.earnedDemoHours = earnedDemoHours;
    }

    public BigDecimal getEarnedMiscHours() {
        return this.earnedMiscHours;
    }

    public void setEarnedMiscHours(BigDecimal earnedMiscHours) {
        this.earnedMiscHours = earnedMiscHours;
    }

    public BigDecimal getEarnedAllEquipHours() {
        return this.earnedAllEquipHours;
    }

    public void setEarnedAllEquipHours(BigDecimal earnedAllEquipHours) {
        this.earnedAllEquipHours = earnedAllEquipHours;
    }

    public BigDecimal getRemainingOffload() {
        return this.remainingOffload;
    }

    public void setRemainingOffload(BigDecimal remainingOffload) {
        this.remainingOffload = remainingOffload;
    }

    public BigDecimal getRemainingSet() {
        return this.remainingSet;
    }

    public void setRemainingSet(BigDecimal remainingSet) {
        this.remainingSet = remainingSet;
    }

    public BigDecimal getRemainingAllign() {
        return this.remainingAllign;
    }

    public void setRemainingAllign(BigDecimal remainingAllign) {
        this.remainingAllign = remainingAllign;
    }

    public BigDecimal getRemainingDemo() {
        return this.remainingDemo;
    }

    public void setRemainingDemo(BigDecimal remainingDemo) {
        this.remainingDemo = remainingDemo;
    }

    public BigDecimal getRemainingMisc() {
        return this.remainingMisc;
    }

    public void setRemainingMisc(BigDecimal remainingMisc) {
        this.remainingMisc = remainingMisc;
    }

    public BigDecimal getRemainingOffloadHours() {
        return this.remainingOffloadHours;
    }

    public void setRemainingOffloadHours(BigDecimal remainingOffloadHours) {
        this.remainingOffloadHours = remainingOffloadHours;
    }

    public BigDecimal getRemainingSetHours() {
        return this.remainingSetHours;
    }

    public void setRemainingSetHours(BigDecimal remainingSetHours) {
        this.remainingSetHours = remainingSetHours;
    }

    public BigDecimal getRemainingAllignHours() {
        return this.remainingAllignHours;
    }

    public void setRemainingAllignHours(BigDecimal remainingAllignHours) {
        this.remainingAllignHours = remainingAllignHours;
    }

    public BigDecimal getRemainingDemoHours() {
        return this.remainingDemoHours;
    }

    public void setRemainingDemoHours(BigDecimal remainingDemoHours) {
        this.remainingDemoHours = remainingDemoHours;
    }

    public BigDecimal getRemainingMiscHours() {
        return this.remainingMiscHours;
    }

    public void setRemainingMiscHours(BigDecimal remainingMiscHours) {
        this.remainingMiscHours = remainingMiscHours;
    }

    public BigDecimal getRemainingAllEquipHours() {
        return this.remainingAllEquipHours;
    }

    public void setRemainingAllEquipHours(BigDecimal remainingAllEquipHours) {
        this.remainingAllEquipHours = remainingAllEquipHours;
    }

    public BigDecimal getPercentComplete() {
        return this.percentComplete;
    }

    public void setPercentComplete(BigDecimal percentComplete) {
        this.percentComplete = percentComplete;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetEquipStatsResponseContent)) return false;
        final GetEquipStatsResponseContent getEquipStatsResponseContent = (GetEquipStatsResponseContent) o;
        return Objects.equals(getBidId(), getEquipStatsResponseContent.getBidId()) &&
                Objects.equals(getProjectServicesRep(), getEquipStatsResponseContent.getProjectServicesRep()) &&
                Objects.equals(getScope(), getEquipStatsResponseContent.getScope()) &&
                Objects.equals(getPhase(), getEquipStatsResponseContent.getPhase()) &&
                Objects.equals(getStage(), getEquipStatsResponseContent.getStage()) &&
                Objects.equals(getTestPackageNumber(), getEquipStatsResponseContent.getTestPackageNumber()) &&
                Objects.equals(getWorkPackage(), getEquipStatsResponseContent.getWorkPackage()) &&
                Objects.equals(getCostCode(), getEquipStatsResponseContent.getCostCode()) &&
                Objects.equals(getP6id(), getEquipStatsResponseContent.getP6id()) &&
                Objects.equals(getP6description(), getEquipStatsResponseContent.getP6description()) &&
                Objects.equals(getAssignedContractor(), getEquipStatsResponseContent.getAssignedContractor()) &&
                Objects.equals(getArea(), getEquipStatsResponseContent.getArea()) &&
                Objects.equals(getLocation(), getEquipStatsResponseContent.getLocation()) &&
                Objects.equals(getStructure(), getEquipStatsResponseContent.getStructure()) &&
                Objects.equals(getCu(), getEquipStatsResponseContent.getCu()) &&
                Objects.equals(getElevation(), getEquipStatsResponseContent.getElevation()) &&
                Objects.equals(getSystem(), getEquipStatsResponseContent.getSystem()) &&
                Objects.equals(getService(), getEquipStatsResponseContent.getService()) &&
                Objects.equals(getEquipmentType(), getEquipStatsResponseContent.getEquipmentType()) &&
                Objects.equals(getActivityType(), getEquipStatsResponseContent.getActivityType()) &&
                Objects.equals(getWbs1(), getEquipStatsResponseContent.getWbs1()) &&
                Objects.equals(getWbs2(), getEquipStatsResponseContent.getWbs2()) &&
                Objects.equals(getWbs3(), getEquipStatsResponseContent.getWbs3()) &&
                Objects.equals(getWbs4(), getEquipStatsResponseContent.getWbs4()) &&
                Objects.equals(getWbs5(), getEquipStatsResponseContent.getWbs5()) &&
                Objects.equals(getWbs6(), getEquipStatsResponseContent.getWbs6()) &&
                Objects.equals(getWbs7(), getEquipStatsResponseContent.getWbs7()) &&
                Objects.equals(getWbs8(), getEquipStatsResponseContent.getWbs8()) &&
                Objects.equals(getWbs9(), getEquipStatsResponseContent.getWbs9()) &&
                Objects.equals(getWbs10(), getEquipStatsResponseContent.getWbs10()) &&
                Objects.equals(getCountOffload(), getEquipStatsResponseContent.getCountOffload()) &&
                Objects.equals(getCountSet(), getEquipStatsResponseContent.getCountSet()) &&
                Objects.equals(getCountAllign(), getEquipStatsResponseContent.getCountAllign()) &&
                Objects.equals(getCountDemo(), getEquipStatsResponseContent.getCountDemo()) &&
                Objects.equals(getCountMisc(), getEquipStatsResponseContent.getCountMisc()) &&
                Objects.equals(getHoursOffload(), getEquipStatsResponseContent.getHoursOffload()) &&
                Objects.equals(getHoursSet(), getEquipStatsResponseContent.getHoursSet()) &&
                Objects.equals(getHoursAllign(), getEquipStatsResponseContent.getHoursAllign()) &&
                Objects.equals(getHoursDemo(), getEquipStatsResponseContent.getHoursDemo()) &&
                Objects.equals(getHoursMisc(), getEquipStatsResponseContent.getHoursMisc()) &&
                Objects.equals(getHoursAll(), getEquipStatsResponseContent.getHoursAll()) &&
                Objects.equals(getInstalledOffload(), getEquipStatsResponseContent.getInstalledOffload()) &&
                Objects.equals(getInstalledSet(), getEquipStatsResponseContent.getInstalledSet()) &&
                Objects.equals(getInstalledAllign(), getEquipStatsResponseContent.getInstalledAllign()) &&
                Objects.equals(getInstalledDemo(), getEquipStatsResponseContent.getInstalledDemo()) &&
                Objects.equals(getInstalledMisc(), getEquipStatsResponseContent.getInstalledMisc()) &&
                Objects.equals(getEarnedOffloadHours(), getEquipStatsResponseContent.getEarnedOffloadHours()) &&
                Objects.equals(getEarnedSetHours(), getEquipStatsResponseContent.getEarnedSetHours()) &&
                Objects.equals(getEarnedAllignHours(), getEquipStatsResponseContent.getEarnedAllignHours()) &&
                Objects.equals(getEarnedDemoHours(), getEquipStatsResponseContent.getEarnedDemoHours()) &&
                Objects.equals(getEarnedMiscHours(), getEquipStatsResponseContent.getEarnedMiscHours()) &&
                Objects.equals(getEarnedAllEquipHours(), getEquipStatsResponseContent.getEarnedAllEquipHours()) &&
                Objects.equals(getRemainingOffload(), getEquipStatsResponseContent.getRemainingOffload()) &&
                Objects.equals(getRemainingSet(), getEquipStatsResponseContent.getRemainingSet()) &&
                Objects.equals(getRemainingAllign(), getEquipStatsResponseContent.getRemainingAllign()) &&
                Objects.equals(getRemainingDemo(), getEquipStatsResponseContent.getRemainingDemo()) &&
                Objects.equals(getRemainingMisc(), getEquipStatsResponseContent.getRemainingMisc()) &&
                Objects.equals(getRemainingOffloadHours(), getEquipStatsResponseContent.getRemainingOffloadHours()) &&
                Objects.equals(getRemainingSetHours(), getEquipStatsResponseContent.getRemainingSetHours()) &&
                Objects.equals(getRemainingAllignHours(), getEquipStatsResponseContent.getRemainingAllignHours()) &&
                Objects.equals(getRemainingDemoHours(), getEquipStatsResponseContent.getRemainingDemoHours()) &&
                Objects.equals(getRemainingMiscHours(), getEquipStatsResponseContent.getRemainingMiscHours()) &&
                Objects.equals(getRemainingAllEquipHours(), getEquipStatsResponseContent.getRemainingAllEquipHours()) &&
                Objects.equals(getPercentComplete(), getEquipStatsResponseContent.getPercentComplete());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getBidId(),
                getProjectServicesRep(),
                getScope(),
                getPhase(),
                getStage(),
                getTestPackageNumber(),
                getWorkPackage(),
                getCostCode(),
                getP6id(),
                getP6description(),
                getAssignedContractor(),
                getArea(),
                getLocation(),
                getStructure(),
                getCu(),
                getElevation(),
                getSystem(),
                getService(),
                getEquipmentType(),
                getActivityType(),
                getWbs1(),
                getWbs2(),
                getWbs3(),
                getWbs4(),
                getWbs5(),
                getWbs6(),
                getWbs7(),
                getWbs8(),
                getWbs9(),
                getWbs10(),
                getCountOffload(),
                getCountSet(),
                getCountAllign(),
                getCountDemo(),
                getCountMisc(),
                getHoursOffload(),
                getHoursSet(),
                getHoursAllign(),
                getHoursDemo(),
                getHoursMisc(),
                getHoursAll(),
                getInstalledOffload(),
                getInstalledSet(),
                getInstalledAllign(),
                getInstalledDemo(),
                getInstalledMisc(),
                getEarnedOffloadHours(),
                getEarnedSetHours(),
                getEarnedAllignHours(),
                getEarnedDemoHours(),
                getEarnedMiscHours(),
                getEarnedAllEquipHours(),
                getRemainingOffload(),
                getRemainingSet(),
                getRemainingAllign(),
                getRemainingDemo(),
                getRemainingMisc(),
                getRemainingOffloadHours(),
                getRemainingSetHours(),
                getRemainingAllignHours(),
                getRemainingDemoHours(),
                getRemainingMiscHours(),
                getRemainingAllEquipHours(),
                getPercentComplete());
    }
}
